version: '3.7'

# Settings and configurations that are common for all containers
x-forges-common: &forges-common
  image: troisforges.io/pesto/api:0.0.1-dev
  build:
    # context: ./backend/oci/dev
    context: .
    dockerfile: backend/oci/dev/Dockerfile
    args:
      PESTO_LX_USER: pesto
      PESTO_LX_USER_GRP: pesto
      # PESTO_LX_PASSWORD: pesto
      PESTO_LX_UID: 1000
      PESTO_LX_GID: 1000
  # command: pnpm dev
  env_file: ./.dev.env
  expose:
    - ${PESTO_API_HTTPS_PORT}/tcp
    - ${PESTO_API_HTTP_PORT}/tcp
  ports:
    - ${PESTO_API_HTTPS_PORT_EXT}:${PESTO_API_HTTPS_PORT}
    - ${PESTO_API_HTTP_PORT_EXT}:${PESTO_API_HTTP_PORT}
  environment:
    PESTO_LX_USER: pesto
    PESTO_LX_USER_GRP: pesto
    # PESTO_LX_PASSWORD: pesto
    PESTO_LX_UID: 1000
    PESTO_LX_GID: 1000
    PESTO_API_ROOT_USER: pesto
    PESTO_API_ROOT_PASSWORD: pesto
    PESTO_API_HOST: app.pesto.io
    PESTO_API_BASE_URL: /api
    PESTO_API_HTTPS_PORT: 9043
    PESTO_API_HTTP_PORT: 9033
    PESTO_SECRETS_FILE: /pesto/.secrets/.secrets.json
  volumes:
    - $PWD/backend/.secrets/.secrets.json:/pesto/.secrets/.secrets.json:ro
  healthcheck:
    test: ["CMD", "curl", "-f", "http://0.0.0.0:9043/pesto/api/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running Pesto Api server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  # minio1:
  #   <<: *forges-common
  #   hostname: minio1
  #   volumes:
  #     - data1-1:/data1
  #     - data1-2:/data2
  # --- 
  # minio2:
  #   <<: *forges-common
  #   hostname: minio2
  #   volumes:
  #     - data2-1:/data1
  #     - data2-2:/data2

  # frontend:
  api:
    <<: *forges-common
  api_database:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.dev.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - api_db:/data/db

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    env_file: ./.dev.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - api
      - api_database
      # - frontend

volumes:
  api_db: {}
