version: '3.7'

# Settings and configurations that are common for all containers
x-forges-common: &forges-common
  image: troisforges.io/pesto/api:dev
  # command: pnpm dev
  expose:
    - "9043"
    - "9033"
  environment:
    PESTO_API_ROOT_USER: pesto
    PESTO_API_ROOT_PASSWORD: pesto
    PESTO_API_BASE_URL: https://app.pesto.io/api
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/pesto/api/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *forges-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *forges-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *forges-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *forges-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
# ---

services:
  frontend:
  api:
  api_database: