version: '3.7'

x-forges-front: &forges-front
  image: "${DOCKER_IMG_ORGNAME}/${DOCKER_IMG_FRONT_NAME}:${DOCKER_IMG_TAG}"
  env_file: ./.dev.env
  volumes:
    - $PWD/pesto.yml:/etc/pesto/pesto.yml:ro
  expose:
    - "3000"
  # ports:
    # - "9980:3000"
  depends_on:
    - api
    - api_database
  networks:
    pesto_back_net:
      aliases:
        - app.pesto.io
    pesto_front_net:
      aliases:
        - app.pesto.io

# Settings and configurations that are common for all backend containers
x-forges-common: &forges-common
  # image: troisforges.io/pesto-api:0.0.1-dev
  image: "${DOCKER_IMG_ORGNAME}/${DOCKER_IMG_BACK_NAME}:${DOCKER_IMG_TAG}"
  # command: pnpm dev
  env_file: ./.dev.env
  expose:
    - ${PESTO_API_HTTPS_PORT}/tcp
    - ${PESTO_API_HTTP_PORT}/tcp
  # ports:
    # - ${PESTO_API_HTTPS_PORT_EXT}:${PESTO_API_HTTPS_PORT}
    # - ${PESTO_API_HTTP_PORT_EXT}:${PESTO_API_HTTP_PORT}
  environment:
    PESTO_LX_USER: pesto
    PESTO_LX_USER_GRP: pesto
    # PESTO_LX_PASSWORD: pesto
    PESTO_LX_UID: 1001
    PESTO_LX_GID: 1001
    PESTO_API_ROOT_USER: pesto
    PESTO_API_ROOT_PASSWORD: pesto
    PESTO_API_HOST: app.pesto.io
    PESTO_API_BASE_URL: /api
    PESTO_API_HTTPS_PORT: 9043
    PESTO_API_HTTP_PORT: 9033
    PESTO_SECRETS_FILE: /pesto/.secrets/.secrets.json
  volumes:
    - $PWD/backend/.secrets/.secrets.json:/pesto/.secrets/.secrets.json:ro
  healthcheck:
    test: ["CMD", "curl", "-f", "http://0.0.0.0:9043/pesto/api/live"]
    interval: 30s
    timeout: 20s
    retries: 3
  networks:
    pesto_back_net:
      aliases:
        - api.pesto.io
    pesto_front_net:
      aliases:
        - api.pesto.io
# starts 4 docker containers running Pesto Api server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  # pesto1:
  #   hostname: app1.pesto.io
  #   networks:
  #     pesto_back_net:
  #       aliases:
  #         - app1.pesto.io
  #     pesto_front_net:
  #       aliases:
  #         - app1.pesto.io


  # pesto2:
  #   hostname: app2.pesto.io
  #   networks:
  #     pesto_back_net:
  #       aliases:
  #         - app2.pesto.io
  #     pesto_front_net:
  #       aliases:
  #         - app2.pesto.io


  # pesto3:
  #   hostname: app3.pesto.io
  #   networks:
  #     pesto_back_net:
  #       aliases:
  #         - app3.pesto.io
  #     pesto_front_net:
  #       aliases:
  #         - app3.pesto.io

  # pesto4:
  #   hostname: app4.pesto.io
  #   networks:
  #     pesto_back_net:
  #       aliases:
  #         - app4.pesto.io
  #     pesto_front_net:
  #       aliases:
  #         - app4.pesto.io


  api:
    <<: *forges-common

  api_database:
    image: mongo:$PESTO_MONGODB_OCI_TAG
    restart: unless-stopped
    env_file: ./.dev.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$PESTO_MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$PESTO_MONGODB_PASSWORD
    ports:
      - $PESTO_MONGODB_LOCAL_PORT:$PESTO_MONGODB_DOCKER_PORT
    volumes:
      - api_db:/data/db
    networks:
      pesto_back_net:
        aliases:
          - db.pesto.io

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    env_file: ./.dev.env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - api
      - api_database
      # - frontend
    networks:
      pesto_back_net:
        aliases:
          - reverse_proxy.pesto.io
      pesto_front_net:
        aliases:
          - reverse_proxy.pesto.io

volumes:
  api_db: {}
networks:
  pesto_back_net:
  pesto_front_net: